$(function(){
	var fadeShow = $(".background").fadeShow({
		correctRatio: true,
		shuffle: true,
		speed: 4000,
		images: ['../img/bg/KathyM.001.jpg',
				 '../img/bg/KathyM.002.jpg',
				 '../img/bg/KathyM.003.jpg',
				 '../img/bg/KathyM.004.jpg',
				 '../img/bg/KathyM.005.jpg',
				 '../img/bg/KathyM.006.jpg',
				 '../img/bg/KathyM.007.jpg',
				 '../img/bg/KathyM.008.jpg',
				 '../img/bg/KathyM.009.jpg',
				 '../img/bg/KathyM.010.jpg',
				 '../img/bg/KathyM.011.jpg',
				 '../img/bg/KathyM.012.jpg',
				 '../img/bg/KathyM.013.jpg',
				 '../img/bg/KathyM.014.jpg',
				 '../img/bg/KathyM.015.jpg',
				 '../img/bg/KathyM.016.jpg',
				 '../img/bg/KathyM.017.jpg',
				 '../img/bg/KathyM.018.jpg',
				 '../img/bg/KathyM.019.jpg',
				 '../img/bg/KathyM.020.jpg',
				 '../img/bg/KathyM.021.jpg',
				 '../img/bg/KathyM.022.jpg',
				 '../img/bg/KathyM.023.jpg',
				 '../img/bg/KathyM.024.jpg',
				 '../img/bg/KathyM.025.jpg',
				 '../img/bg/KathyM.026.jpg',
				 '../img/bg/KathyM.027.jpg',
				 '../img/bg/KathyM.028.jpg',
				 '../img/bg/KathyM.029.jpg',
				 '../img/bg/KathyM.030.jpg',
				 '../img/bg/KathyM.031.jpg',
				 '../img/bg/KathyM.032.jpg'
		]
	});
});
